// ignore_for_file: constant_identifier_names

class Zambia {
  static const List<String> Provinces = [
    "Central Province",
    "Copperbelt Province",
    "Eastern Province",
    "Luapula Province",
    "Lusaka Province",
    "Muchinga Province",
    "Northern Province",
    "North-Western Province",
    "Southern Province",
    "Western Province",
  ];

  static const Map<String, List<String>> Districts = {
    "Central Province": [
      "Chibombo",
      "Chisamba",
      "Chitambo",
      "Kabwe",
      "Kapiri Mposhi",
      "Luano",
      "Mkushi",
      "Mumbwa",
      "Ngabwe",
      "Serenje",
      "Shibuyunji",
    ],
    "Copperbelt Province": [
      "Chililabombwe",
      "Chingola",
      "Kalulushi",
      "Kitwe",
      "Luanshya",
      "Lufwanyama",
      "Masaiti",
      "Mpongwe",
      "Mufulira",
      "Ndola",
    ],
    "Eastern Province": [
      "Chadiza",
      "Chama",
      "Chasefu",
      "Chipangali",
      "Chipata",
      "Kasenengwa",
      "Katete",
      "Lumezi",
      "Lundazi",
      "Lusangazi",
      "Mambwe",
      "Nyimba",
      "Petauke",
      "Sinda",
      "Vubwi",
    ],
    "Luapula Province": [
      "Chembe",
      "Chiengi",
      "Chifunabuli",
      "Chipili",
      "Kawambwa",
      "Lunga",
      "Mansa",
      "Milenge",
      "Mwansabombwe",
      "Mwense",
      "Nchelenge",
      "Samfya",
    ],
    "Lusaka Province": [
      "Chilanga",
      "Chongwe",
      "Kafue",
      "Luangwa",
      "Lusaka",
      "Rufunsa",
    ],
    "Muchinga Province": [
      "Chinsali",
      "Isoka",
      "Kanchibiya",
      "Lavushimanda",
      "Mafinga",
      "Mpika",
      "Nakonde",
      "Shiwang'andu",
    ],
    "Northern Province": [
      "Chilubi",
      "Kaputa",
      "Kasama",
      "Lunte",
      "Lupososhi",
      "Luwingu",
      "Mbala",
      "Mporokoso",
      "Mpulungu",
      "Mungwi",
      "Nsama",
      "Senga",
    ],
    "North-Western Province": [
      "Chavuma",
      "Ikelenge",
      "Kabompo",
      "Kasempa",
      "Kalumbila",
      "Manyinga",
      "Mufumbwe",
      "Mushindamo",
      "Mwinilunga",
      "Solwezi",
      "Zambezi",
    ],
    "Southern Province": [
      "Chikankata",
      "Chirundu",
      "Choma",
      "Gwembe",
      "Itezhi-Tezhi",
      "Kalomo",
      "Kazungula",
      "Livingstone",
      "Mazabuka",
      "Monze",
      "Namwala",
      "Pemba",
      "Siavonga",
      "Sinazongwe",
      "Zimba",
    ],
    "Western Province": [
      "Kalabo",
      "Kaoma",
      "Limulunga",
      "Luampa",
      "Lukulu",
      "Mitete",
      "Mongu",
      "Mulobezi",
      "Mwandi",
      "Nalolo",
      "Nkeyema",
      "Senanga",
      "Sesheke",
      "Shang'ombo",
      "Sikongo",
      "Sioma",
    ],
  };
}
